Feature/cheerio
FlowiseAI/FlowiseDocs pull request #51
Opened 2024-02-04 08:53 UTC by chungyau97

2024-02-05 13:48 UTC, 0xi4o commented on integrations/document-loaders/cheerio-web-scraper.md
> +## Mange Links
Typo: "Manage Links"

2024-02-05 13:48 UTC, 0xi4o commented on integrations/document-loaders/cheerio-web-scraper.md
> +2.  _(Optional)_ Input dsired URL to be scrape.
Typo: "desired"

2024-02-05 13:49 UTC, 0xi4o commented
@chungyau97 Can you also mention that the documentation applies for `Puppeteer` and `Playwright` as well? They steps are exactly the same.

2024-02-05 13:51 UTC, 0xi4o requested changes
1. Couple of typos
2. Mention that the same steps apply for `Puppeteer` and `Playwright`.

2024-02-05 22:11 UTC, chungyau97 commented
@0xi4o, which do you think will be the best?
Re-create the same steps in `Puppeteer` and `Playwright`
or
`Cheerio`, `Puppeteer` and `Playwright` reference to another page on how to scrape multiple links.

2024-02-06 03:32 UTC, 0xi4o commented
@chungyau97 Referencing `Cheerio` in `Puppeteer` and `Playwright` would be better since we don't have to copy over the exact same steps and have one source of truth.

2024-02-09 08:14 UTC, 0xi4o approved these changes

2024-02-10 04:08 UTC, merged