Update azure.md
FlowiseAI/FlowiseDocs pull request #9
Opened 2023-07-13 06:06 UTC by athuls1992

Added complete steps to resolve persistent storage issue when deploying in Azure container

2023-07-13 07:46 UTC, meaboutsoftware requested changes

2023-07-13 07:46 UTC, meaboutsoftware commented on deployment/azure.md
> +##Persistent Disk in Container Apps
I am voting to not to accept this solution as it is unstable due to the nature of sqlite (that is designed to not to be a database for concurrent users) and poor integration with File Share. It sometimes saves the data, sometimes not, sometimes is able to read and sometimes not.

I am now testing the solution with a file share as store (without sqllite), similar as it is done in Render.

2023-07-13 07:46 UTC, meaboutsoftware commented on deployment/azure.md
> +
I am lacking the step to configure an environment variable for DATABASE_PATH

2023-07-13 09:05 UTC, dabrodev commented on deployment/azure.md
> +
The actual documentation ends with 7. Visit your Flowise instance by clicking on "Application Url".
Where should I provide mount path to a selected fileshare? How  do I setup fileshare? Where should I select the basics tab?

2023-07-13 09:13 UTC, meaboutsoftware requested changes
I would wait with description of this solution due to instability. It does not work as expected - sometimes read existing chatflows, sometimes not, sometimes saves, sometimes not.

2023-07-16 12:15 UTC, meaboutsoftware commented
I vote to close this PR without merging. Look at PR #10.

2023-07-16 13:59 UTC, HenryHengZJ commented
closing as #10 merged

2023-07-16 13:59 UTC, closed without merging